modLoader="javafml" #mandatory

loaderVersion="[35,)" #mandatory

license="All rights reserved"

[[mods]] #mandatory

modId="xlifehealth" #mandatory

version="1.6.0" #mandatory

displayName="X Life Health Mod" #mandatory

logoFile="xlifemod.png" #optional

credits="Thanks for this mod goes to Java" #optional

authors="DaqEm" #optional

description="X Life Health Mod Made By DaqEm."

[[dependencies.xlifehealth]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
